# Generated by Django 5.1 on 2026-03-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_urls", models.IntegerField(default=0)),
                ("new_urls", models.IntegerField(default=0)),
                ("max_depth", models.IntegerField(default=3)),
                ("max_pages", models.IntegerField(default=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanDiff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("new_urls_count", models.IntegerField(default=0)),
                ("removed_urls_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_as_current",
                        to="scans.scan",
                    ),
                ),
                (
                    "previous_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_as_previous",
                        to="scans.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveredURL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(db_index=True, max_length=2048)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("html", "HTML Link"),
                            ("js", "JavaScript"),
                            ("robots", "robots.txt"),
                            ("sitemap", "sitemap.xml"),
                            ("bruteforce", "Bruteforce"),
                        ],
                        default="html",
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, default="", max_length=255)),
                ("depth", models.IntegerField(default=0)),
                ("is_internal", models.BooleanField(default=True)),
                ("is_new", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="scans.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen"],
                "unique_together": {("scan", "url")},
            },
        ),
        migrations.CreateModel(
            name="DiffURL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=2048)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("added", "Added"), ("removed", "Removed")],
                        max_length=10,
                    ),
                ),
                (
                    "diff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diff_urls",
                        to="scans.scandiff",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="discoveredurl",
            index=models.Index(fields=["scan", "is_new"], name="scans_disco_scan_id_5a2fd6_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveredurl",
            index=models.Index(fields=["scan", "source"], name="scans_disco_scan_id_9371a5_idx"),
        ),
    ]
