# Generated by Django 5.1 on 2026-03-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_improve_structure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='scans_disco_scan_id_857bce_idx',
            old_name='scans_disco_scan_id_5a2fd6_idx',
        ),
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='scans_disco_scan_id_169bd7_idx',
            old_name='scans_disco_scan_id_9371a5_idx',
        ),
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='scans_disco_scan_id_1347f4_idx',
            old_name='scans_disco_scan_id_intern_idx',
        ),
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='scans_disco_scan_id_29aca8_idx',
            old_name='scans_disco_scan_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='discoveredurl',
            new_name='scans_disco_scan_id_d71d53_idx',
            old_name='scans_disco_scan_id_extdom_idx',
        ),
    ]
