# Generated by Django 5.1 on 2026-03-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_rename_scans_alert_site_date_idx_scans_exter_site_do_30ab13_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('check_status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('safe_browsing_result', models.JSONField(blank=True, default=dict, help_text='Google Safe Browsing API response data')),
                ('safe_browsing_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('virustotal_stats', models.JSONField(blank=True, default=dict, help_text='VirusTotal analysis statistics')),
                ('virustotal_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('virustotal_malicious', models.IntegerField(default=0)),
                ('virustotal_suspicious', models.IntegerField(default=0)),
                ('virustotal_harmless', models.IntegerField(default=0)),
                ('virustotal_undetected', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('check_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domainreputation',
            index=models.Index(fields=['risk_level'], name='scans_domai_risk_le_c2b5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='domainreputation',
            index=models.Index(fields=['check_status'], name='scans_domai_check_s_e87d64_idx'),
        ),
        migrations.AddIndex(
            model_name='domainreputation',
            index=models.Index(fields=['checked_at'], name='scans_domai_checked_d7312a_idx'),
        ),
    ]
