# Generated by Django 5.1 on 2026-03-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_domainreputation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=15, help_text='How often (minutes) to run a light scan')),
                ('key_pages', models.JSONField(blank=True, default=list, help_text='Relative paths to monitor, e.g. ["/","/login","/checkout"]')),
                ('last_content_hash', models.CharField(blank=True, default='', help_text='MD5 hash of aggregated key-page content from last scan', max_length=64)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('next_scan_at', models.DateTimeField(blank=True, null=True)),
                ('total_light_scans', models.PositiveIntegerField(default=0)),
                ('changes_detected_count', models.PositiveIntegerField(default=0)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Monitor Config',
                'verbose_name_plural': 'Site Monitor Configs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='externaldomainalert',
            name='domain_list',
            field=models.JSONField(blank=True, default=list, help_text='List of domains related to this alert'),
        ),
        migrations.AlterField(
            model_name='externaldomainalert',
            name='alert_type',
            field=models.CharField(choices=[('new_domain', 'New External Domain'), ('suspicious_domain', 'Suspicious Domain'), ('removed_domain', 'Domain Removed'), ('content_change', 'Content Changed'), ('domain_removed', 'Domain No Longer Found')], max_length=30),
        ),
        migrations.AlterField(
            model_name='externaldomainalert',
            name='external_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='externaldomainalert',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scans.scan'),
        ),
        migrations.CreateModel(
            name='LightScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('has_changes', models.BooleanField(default=False)),
                ('pages_checked', models.PositiveIntegerField(default=0)),
                ('pages_data', models.JSONField(blank=True, default=list, help_text='Per-page status: [{url, status_code, hash, has_content}]')),
                ('external_domains_snapshot', models.JSONField(blank=True, default=list, help_text='All external domains found in this scan')),
                ('new_domains', models.JSONField(blank=True, default=list, help_text='Domains found in this scan but not in previous')),
                ('removed_domains', models.JSONField(blank=True, default=list, help_text='Domains in previous scan but not in this one')),
                ('new_domains_count', models.PositiveIntegerField(default=0)),
                ('removed_domains_count', models.PositiveIntegerField(default=0)),
                ('reputation_enqueued', models.BooleanField(default=False, help_text='Whether new domains were sent to the reputation queue')),
                ('scan_duration', models.FloatField(default=0.0, help_text='Scan duration in seconds')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_scan_results', to='scans.sitemonitorconfig')),
            ],
            options={
                'verbose_name': 'Light Scan Result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site_config', '-created_at'], name='scans_light_site_co_ce3c35_idx'), models.Index(fields=['has_changes'], name='scans_light_has_cha_e67f40_idx')],
            },
        ),
    ]
