# Generated by Django 5.1 on 2026-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_sitemonitorconfig_externaldomainalert_domain_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldomainentry',
            name='list_classification',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Classification based on whitelist/blacklist', max_length=10),
        ),
        migrations.AlterField(
            model_name='externaldomainalert',
            name='alert_type',
            field=models.CharField(choices=[('new_domain', 'New External Domain'), ('suspicious_domain', 'Suspicious Domain'), ('removed_domain', 'Domain Removed'), ('content_change', 'Content Changed'), ('domain_removed', 'Domain No Longer Found'), ('blacklist_hit', 'Blacklisted Domain Found')], max_length=30),
        ),
        migrations.CreateModel(
            name='DomainListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_domain', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, help_text='External domain pattern, e.g. google.com', max_length=255)),
                ('list_type', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], db_index=True, max_length=10)),
                ('note', models.TextField(blank=True, default='', help_text='Optional reason / comment')),
                ('added_by', models.CharField(default='user', help_text='Who added: user | auto-suggest', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domain List Entry',
                'verbose_name_plural': 'Domain List Entries',
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['site_domain', 'list_type'], name='scans_domlist_site_type_idx')],
                'unique_together': {('site_domain', 'domain', 'list_type')},
            },
        ),
    ]
