# Generated by Django 5.1 on 2026-03-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_externaldomainentry_list_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('form', 'Form Login'), ('cookie', 'Cookie')], default='none', max_length=10)),
                ('is_enabled', models.BooleanField(default=False)),
                ('login_url', models.URLField(blank=True, default='', max_length=2048)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password_encrypted', models.TextField(blank=True, default='', help_text='AES-encrypted password')),
                ('username_selector', models.CharField(blank=True, default='', help_text='CSS selector for username field, e.g. #email or input[name=username]', max_length=255)),
                ('password_selector', models.CharField(blank=True, default='', help_text='CSS selector for password field, e.g. #password', max_length=255)),
                ('submit_selector', models.CharField(blank=True, default='', help_text='CSS selector for submit button, e.g. button[type=submit]', max_length=255)),
                ('cookie_value', models.TextField(blank=True, default='', help_text='Raw cookie string, e.g. sessionid=abc123; token=xyz')),
                ('auth_status', models.CharField(choices=[('untested', 'Not Tested'), ('success', 'Login Successful'), ('failed', 'Login Failed')], default='untested', max_length=10)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('session_cookies', models.JSONField(blank=True, default=dict, help_text='Cookies obtained after successful login')),
                ('session_valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Auth Config',
                'verbose_name_plural': 'Site Auth Configs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='discoveredurl',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this URL was discovered via authenticated scanning'),
        ),
        migrations.AddField(
            model_name='scan',
            name='private_urls',
            field=models.IntegerField(default=0),
        ),
    ]
