# Generated by Django 5.1 on 2026-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_siteauthconfig_discoveredurl_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldomainalert',
            name='alert_type',
            field=models.CharField(choices=[('new_domain', 'New External Domain'), ('suspicious_domain', 'Suspicious Domain'), ('removed_domain', 'Domain Removed'), ('content_change', 'Content Changed'), ('domain_removed', 'Domain No Longer Found'), ('blacklist_hit', 'Blacklisted Domain Found'), ('auth_failed', 'Authentication Failed'), ('session_expired', 'Session Expired'), ('new_private_page', 'New Private Page Discovered')], max_length=30),
        ),
    ]
