# Generated by Django 5.1 on 2026-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_alter_externaldomainalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredurl',
            name='is_sensitive',
            field=models.BooleanField(db_index=True, default=False, help_text='True if URL matches sensitive page patterns (/admin, /settings, /billing, etc.)'),
        ),
        migrations.AddField(
            model_name='siteauthconfig',
            name='auth_strategy',
            field=models.CharField(choices=[('auto', 'Auto (HTTP → Browser fallback)'), ('http_only', 'HTTP Only'), ('playwright_only', 'Browser Only (Playwright)')], default='auto', help_text='Login method strategy: auto, http_only, or playwright_only', max_length=20),
        ),
    ]
