# Generated by Django 5.1 on 2026-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_add_auth_strategy_and_is_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteauthconfig',
            name='home_url',
            field=models.URLField(blank=True, default='', help_text='Homepage URL where the login button is located', max_length=2048),
        ),
        migrations.AddField(
            model_name='siteauthconfig',
            name='login_button_selector',
            field=models.CharField(blank=True, default='', help_text='CSS selector for the login button on homepage that opens the login form/modal', max_length=255),
        ),
        migrations.AddField(
            model_name='siteauthconfig',
            name='recorded_steps',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of recorded login steps: [{action, selector, value, ...}]'),
        ),
        migrations.AlterField(
            model_name='siteauthconfig',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('form', 'Form Login'), ('cookie', 'Cookie'), ('interactive', 'Interactive Login'), ('recorded', 'Recorded Flow')], default='none', max_length=20),
        ),
    ]
