# Generated by Django 5.1 on 2026-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_interactive_recorded_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='auth_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scan',
            name='auth_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scan',
            name='auth_success',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
